### ISSUE TITLE
html reporter does not render source files

### ISSUE THREAD

**Issue by SamNelson** [istanbuljs/istanbuljs#39]
On some of my files the html reporting is failing. Instead of rendering the source code annotated with coverage it is rendering the following stack trace:
```
Cannot read property 'start' of undefined
TypeError: Cannot read property 'start' of undefined
    at /Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:50:28
    at Array.forEach (native)
    at annotateStatements (/Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:46:33)
    at Object.annotateSourceCode (/Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:193:9)
    at HtmlReport.onDetail (/Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:217:39)
    at LcovReport.(anonymous function) [as onDetail] (/Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:24:24)
    at Visitor.(anonymous function) [as onDetail] (/Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /Users/snels/projects/halo-api/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
```

Digging into the that stack trace it looks like html/annotator.js assumes that *fileCoverage.s* and *fileCoverage.statementMap* are always the same length.
```
var statementStats = fileCoverage.s,
        statementMeta = fileCoverage.statementMap;
    Object.keys(statementStats).forEach(function (stName) {
        var count = statementStats[stName],
            meta = statementMeta[stName],
            type = count > 0 ? 'yes' : 'no',
            startCol = meta.start.column,
            endCol = meta.end.column + 1,
            startLine = meta.start.line,
            endLine = meta.end.line,
            openSpan = lt + 'span class="' + (meta.skip ? 'cstat-skip' : 'cstat-no') + '"' + title('statement not covered') + gt,
            closeSpan = lt + '/span' + gt,
            text;
```

However in the case where it fails this is not the case. In my case, the lcov.info file *s* contains extra entries ('statementMap' only has entries up to "16"):
```
"s": {
      "0": 2,
      "1": 4,
      "2": 5,
      "3": 4,
      "4": 2,
      "5": 1,
      "6": 4,
      "7": 4,
      "8": 3,
      "9": 3,
      "10": 4,
      "11": 6,
      "12": 4,
      "13": 4,
      "14": 6,
      "15": 4,
      "16": 4,
      "17": null,
      "18": null,
      "19": null
    },
```
This could easily be fixed by filtering the keys or adding a guard clause inside the forEach handling function.

**Comment by bcoe** [comment]
@SamNelson mind sharing your configuration -- mainly I'm curious whether you're using source-maps? there's a chance this is related to a mapping bug that I fixed on the `next` branch  of nyc:

`npm i nyc@next`

**Comment by SamNelson** [comment]
I tried `npm i nyc@next` and still had the same problem. I've also tried setting source maps to true.
Here's my config:
Snippets from `package.json`
```
"devDependencies": {
  "babel-plugin-istanbul": "^4.1.1",
  "nyc": "^10.3.0-candidate.0"
}
"nyc": {
    "require": [
      "babel-register"
    ],
    "include": [
      "src/*/**"
    ],
    "sourceMap": false,
    "instrument": false
  }
```
Snippets from `.babelrc`
```
{
  "presets": [
    "es2015-node", "stage-0"
  ],
  "sourceMaps": false,
  "env": {
    "test": {
      "plugins": [
        "babel-plugin-rewire", "istanbul"
      ]
    }
  }
}
```
Did you see my pull request? It seems to fix the problem.

**Comment by bcoe** [comment]
aha! I was curious whether you were using rewire; I landed a fix the other week that hasn't gone out yet, which I think will solve your underlying issue:

https://github.com/istanbuljs/istanbuljs/pull/38

**Comment by SamNelson** [comment]
@bcoe I pulled in your changes and ran `npm run release` in the *istanbul-lib-instrument* directory.
Next, I copied *dist/vistitor.js* to my project's *node_modules/nyc/node_modules/istanbul-lib-instrument/dist/* with the hope that this would hack your changes into my project.
I'm still seeing the same problem though.

**Comment by bcoe** [comment]
@SamNelson also worth noting, rewire indicates that the order should be reversed when pulling in the plugins:

https://github.com/speedskater/babel-plugin-rewire#istanbul

`['istanbuljs', 'rewire']`

Also, _I think_ you want to use `rewire` rather than `babel-plugin-rewire`.

**Comment by bcoe** [comment]
@SamNelson mainly I'd like to find the root cause for the lines being out of whack, rather than masking the issue (since it will result in hiding bad coverage information).

**Comment by bcoe** [comment]
@SamNelson did you get a chance to try reversing the order of Istanbul and Rewire? If this does solve the problem, any ideas as to where we could document this on Istanbul's side, to make this bug harder to run into?

**Comment by SamNelson** [comment]
@bcoe Reversing the order resolves the problem. As far as documentation goes, maybe something in the readme for babel-plugin-istanbul would be a good place to document this this fix.

**Comment by bcoe** [comment]
@SamNelson closing this issue as fixed 👍 thanks for helping figure this out. If you have a moment, I'd happily accept a patch for the docs.
