### ISSUE TITLE
why is a constructor parameter considered a branch and not covered?

### ISSUE THREAD

**Issue by daBishMan** [istanbuljs/istanbuljs#70]
Hello all,

Thanks for great work, and sorry if this is not the right forum to ask this question.  
![image](https://user-images.githubusercontent.com/5060855/27486581-496c601a-57ee-11e7-8fac-4a934f68a8a6.png)

As you can see from the image above, the constructor params are considered branch and are not covered, the rest of the class is 100% expect the constructor.

Can you tell me why it is counting the constructor as branches, and how can I fix it, please?

**Comment by ChrisLebbano** [comment]
I am having the same issue.  I found some fix that uses comments to ignore lines of code like /* istanbul ignore next */ but these do not work at all.

**Comment by EugeneSnihovsky** [comment]
+1
Have same issue and `/* istanbul ignore next */` not helped.

**Comment by bashirsouid** [comment]
+1
We are also having this same issue come up when using this for code coverage in our Angular2 application that uses the standard @input decorator.

```
import { Component, Input } from '@angular/core';
import { PluginOptions } from '../../../plugin-contracts';
import { Template } from '../../../plugin-contracts';
 
@Component({
    selector: 'angular-component',
    templateUrl: './angular-component.component.html',
    styleUrls: ['./angular-component.component.scss'],
})
export class AngularComponent {
    /* istanbul ignore next */
    @Input()
    pluginOptions: PluginOptions;
 
    /* istanbul ignore next */
    @Input()
    template: Template;
}
```

The code coverage shows up as missing branches in the @input decorator which is just an interface. There is no way to directly ignore this?

Any ideas?

**Comment by bcoe** [comment]
@daBishMan @EugeneSnihovsky I will make sure we have a test case around constructors in the tests for the instrumenter.

Unfortunately, as with #72, when a transpiler is being used to shim language features the generated code can sometimes introduce branches that are difficult to cover -- what does the constructor ultimately look like, when run through the TypeScript compiler?

**Comment by troythacker** [comment]
I am experiencing the same issues as @EugeneSnihovsky and @daBishMan.

One of the failing constructors is simple:
```typescript
public constructor(private renderer: Renderer2) { }
``` 

and the transpiled javascript is:
```javascript
function SearchComponent(renderer) {
   this.renderer = renderer;
}
```
but when running coverage, I get the following result:

![screenshot 2017-09-20 06 34 40](https://user-images.githubusercontent.com/15794620/30646422-d2670968-9dcd-11e7-903b-29e09206f9be.png)

**Comment by Remco75** [comment]
I have exactly the same in an angular4 env.
the classes are decorated with the angular @injectable decorator. Maybe that causes this?

**Comment by texasinstrument** [comment]
+1

I tried using `/* istanbul ignore next */` but it doesn't work for the comma syntax for constructor. Anyone found a workaround?

**Comment by stewshka** [comment]
Having this problem too =( wrong lines/coverage for typescript

**Comment by anubhavgupta** [comment]
Any ETA on this issue please?

**Comment by siropeich** [comment]
I found a (quite ugly) workaround by adding `any` to the type of the parameters causing it:
```js
constructor(@inject(TYPES.IDataProvider) private dataProvider: IDataProvider | any) {
}
```

**Comment by otroboe** [comment]
I'm interested by a solution too, I'm working with NestJS, and I have the same issue.

**Comment by lvalencia** [comment]
Same issue here +1 NestJS

**Comment by ericzon** [comment]
+1 I'm using NestJs too
I prefer to wait until there's a good solution for this, I appreciate so much my type-ahead & checking...

**Comment by tedp** [comment]
I'm also having the same issue when using Jest with Angular 5 and Typescript.  Is this something that is being addressed as of now or at least in the pipeline to be fixed?

**Comment by pie6k** [comment]
![image](https://user-images.githubusercontent.com/7311462/40545596-b1f4b230-602c-11e8-9083-3f4f16d6450b.png)

I'm having similar issue. No idea what is not covered here.

**Comment by dWhisper** [comment]
Seeing the same issue, making the branch metrics on the coverage report unreliable.

**Comment by mcblum** [comment]
We're seeing the same thing on Angular 5 + Jest. It's not every single line in the constructor, which is weird. Sometimes there will be three things being injected and it will just be one line or so that's showing as uncovered.

**Comment by harrison-ifeanyichukwu** [comment]
Hello guys. I can confirm that i just discovered a fix for this. I was working on an open source project here [forensic-js](https://github.com/harrison-ifeanyichukwu/forensic-js) when i bumped into this problem, I had to dig in and thankfully, i was able to find a fix.

**Here is my Report and Fix**

First of all, this issue arises when your class extends another class. It does not happen if your class does not extend another class.

**What then is the Cause**?

The cause is that when a class `extends` another class, The class `constructor` is obligated to call `super()` before any other code. To maintain this, the transpiler introduces a branching by inject the code below into your constructor while trying to locate the super class `this` object.

```javascript
var _this = possibleConstructorReturn(this, (_DOMTokenList.__proto__ ||
Object.getPrototypeOf(_DOMTokenList)).call(this, null, true, true));
```
As you can see, it tries to access it using the deprecated `__proto__` property, else it uses the standard `Object.getPrototypeOf()`. Note that _DOMTokenList is the class name of the module i was working on.

**What Then is the Fix?**

The fix is creating an instance of your class two times to statisfy those conditions, and thankfully, the `__proto` property is both a `getter` and a `setter`. 

Here is how i did it:
```javascript
let instance = null,
proto = MyClassName.__proto__;

//lets satisfy condition 1
MyClassName.__proto__ = null;
//put in try catch because it throws error
try {
    instance = new MyClassName(...args);
}
catch(ex){}

//lets satisfy condition two, set back the proto
MyclassName.__proto__ = proto;
instance = new MyClassName(...args);
```

Thats it. you can wrap this into a function and make it reusable across tests. Hope this makes someone smile.... lol.

**Comment by mikeesouth** [comment]
I'm having the same problem but I can't get your fix to work @harrison-ifeanyichukwu 
Any other tips or suggested workarounds for this issue would be appreciated.

**Comment by harrison-ifeanyichukwu** [comment]
@mikeesouth, this issue all depends on the nature of your constructor, and a better way for me to offer any other suggestion is by having a look at the final build. if you don't mind, you can paste the line of code that is not covered here, or my email harrisonifeanyichukwu@gmail.com.. if it is an open source project, i can replicate it from my end as well if given the link. thanks

**Comment by rhogeranacleto** [comment]
Hi @harrison-ifeanyichukwu, how are you doing?

I'm having the same problem as well. Coverage report doesn't give a real feedback, the branch coverage in reports is 88%, but I've tested 100% of my code. I created a simulation in the following link  https://github.com/rhogeranacleto/branch-not-covered-simulation, have a look into the `modules/gate gate.controller.ts`:

![image](https://user-images.githubusercontent.com/4934413/42965939-e1768c3e-8b71-11e8-81c7-06940fc71c4f.png)

And in `modules/gate gate.entity.ts` as well:
![captura de tela de 2018-07-19 16-37-58](https://user-images.githubusercontent.com/4934413/42966061-442d9976-8b72-11e8-9c02-11171e9331fe.png)

**Do you have any suggestion?**

**Comment by harrison-ifeanyichukwu** [comment]
Hi @rhogeranacleto , hope you are doing great,

I have been looking into your issue, I think your problem all boils down to the use decorators. Though it is different from my own problem and suggested fix, below is my suggestion based on my findings.

The decorators introduces branching and your tests have to cover this scenerios

**Concerning `getAll()` method on line 14, in file gates.controller.ts:**

The `@Get()` decorator takes an optional path argument. Below is the prototype from nestjs:

```javascript
export declare const Get: (path?: string) => MethodDecorator;
```

This introduces a branch. Therefore, your test should cover both situations, you should test when a path argument is supplied and when a path argument is not supplied.


The second problem on the same line is that the `@Query(PaginationPipe)`
takes a comma separated list of `Type<PipeTransform>` or `PipeTransform` arguments. below is the prototype from nestjs:

```javascript
export declare function Query(...pipes: (Type<PipeTransform> | PipeTransform)[]): any;
```

Your test should cover both scenerio. test when the argument is of type `Type<PipeTransform>`
and when the argument is of type `PipeTransform`, also test when there are no arguments too.

For other similar lines, use your text editor's go to definition functionality, you will see the prototype of these decorators from your nestjs node module. and fix the issues using my logic here. Thanks

I hope this rectifies your case.

**Comment by rhogeranacleto** [comment]
Who is passing by **branch not covered** in randoms statements just add **ignoreCoverageForAllDecorators** described on [**ts-jest** documentation](https://github.com/kulshekhar/ts-jest#ignore-coverage-on-decorators). Will works for the most of cases I guess.
Hope this helps! :slightly_smiling_face:

**Comment by itslenny** [comment]
@rhogeranacleto is this still working for you? I tried it, but it didn't seem to change anything.

**Comment by rhogeranacleto** [comment]
@itslenny in some cases yes. As you can see on print screens below:

class 1 before config | class 2 before config
:---: | :---:
![class with no coverage](https://user-images.githubusercontent.com/4934413/44851686-7de2e280-ac37-11e8-8b91-c4ce288b43c0.png) | ![controller with no coverage](https://user-images.githubusercontent.com/4934413/44851697-876c4a80-ac37-11e8-916e-0388cbff1b78.png)
class 1 after config | class 2 after config
![class with coverage](https://user-images.githubusercontent.com/4934413/44851830-f053c280-ac37-11e8-8197-39793abcd517.png) | ![controller with coverage](https://user-images.githubusercontent.com/4934413/44851837-f3e74980-ac37-11e8-96a5-d2565925495a.png)

As we can see, the only thing I can't fix it is the **coverage on dependency injection**. Anyone with a workaround would be very pleasurable. :upside_down_face: :upside_down_face:

**Comment by timtrinidad** [comment]
I ran into this issue with `ts-jest` and `inversify`.

After some debugging, I found that `tsc` compiled the `@provides` or `@fluentProvide` decorators into the following 
```
MysqlClient = MysqlClient_1 = __decorate([
    inversify_binding_decorators_1.fluentProvide(MysqlClient_1)
        .inSingletonScope()
        .done(),
    __metadata("design:paramtypes", [connection_1.MysqlConnection])
], MysqlClient);
```

but for some reason `ts-jest` compiled it into the following: 
```
MysqlClient = MysqlClient_1 = /* istanbul ignore next */__decorate([
    inversify_binding_decorators_1.fluentProvide(MysqlClient_1)
        .inSingletonScope()
        .done(),
    __metadata("design:paramtypes", [typeof (_a = typeof connection_1.MysqlConnection !== "undefined" && connection_1.MysqlConnection) === "function" ? _a : Object])
], MysqlClient);
```
Looking at the [source map visualization](https://github.com/sokra/source-map-visualization), it's that `typeof` ternary that's causing an uncovered branch. I wasn't sure why it only showed up when transpiled with `ts-jest` and not `tsc`.
![image](https://user-images.githubusercontent.com/2067202/45574532-55b1d100-b83e-11e8-9d53-25499f15d07e.png)

In any case, we solved this by setting `emitDecoratorMetadata: false` as a compiler option for `ts-jest`.

```
// jest.config.js
module.exports = {
  // ... other settings ...
  globals: {
    'ts-jest': {
      tsConfigFile: 'tsconfig.jest.json',
    },
  },
};
```

```
// tsconfig.jest.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": false
  }
}
```

**Comment by rhogeranacleto** [comment]
@timtrinidad If I turn **emitDecoratorMetadata** to false on my **tsconfig.spec.json**, all my tests with decorators on file are failed :disappointed_relieved:

**Comment by timtrinidad** [comment]
Yes - this solution will only work if your tests do not rely on the decorators (e.g. unit tests)

**Comment by danil-z** [comment]
here is simple repo to reproduce

https://github.com/danil-z/covjest

**Comment by rhogeranacleto** [comment]
### Hey everyone! :smiley: 

For who is using *jest*, *ts-jest* and *typescript*: The **ts-jest** has released version **23.10.4** that fix this issue, now my coverage is ~wonderfully~ 100% :tada: !!

before | after
--- | ---
![image](https://user-images.githubusercontent.com/4934413/49082661-7ed4e180-f231-11e8-9407-a6f01b6de044.png) | ![image](https://user-images.githubusercontent.com/4934413/49082397-ce66dd80-f230-11e8-97a4-d985f181b77f.png)


Thanks for everything :heart: ! Hope it helps! :wink:

**Comment by ahnpnl** [comment]
Please check jest-preset-angular at 7.0.0-alpha.2 if you are using jest in your Angular app. The issue with coverage was fixed 🙂

**Comment by segtio** [comment]
@ahnpnl i tried jest-preset-angular at 7.0.0-alpha.2  but having a **Preset jest-preset-angular not found** error on test launch

**Comment by ahnpnl** [comment]
Hi @segtio, please submit an issue regarding to your issue in jest-preset-angular repo with your project configuration. It will be easier to check what is the error and what is your project configuration :)

**Comment by mohyeid** [comment]
@ahnpnl This is perfect! jest-preset-angular at 7.0.0-alpha.2 made it. 
Do you know when version 7 will be released?

**Comment by Rush** [comment]
I have ts-jest 24 and jest-preset-angular but I'm still seeing the issue with coverage and dependency injection. Any tips?

**Comment by luchsamapparat** [comment]
I have the same issue with an up-to-date Nx Workspace

**Comment by nicolaspearson** [comment]
Settting the preset to `ts-jest` in the `jest.config.js` file worked for me:

```
module.exports = {
  ...
  preset: 'ts-jest',
  ...
}
```

**Comment by walterspieler** [comment]
> I'm interested by a solution too, I'm working with NestJS, and I have the same issue.

Did find a workaround for NestJS ? I have the same issue but only on one service on the whole app.

**Comment by otroboe** [comment]
@walterspieler 
I don't remember I'm sorry, it's been a long time! I still have a repo, but it's quite simple and old:
https://github.com/otroboe/nestjs-playground

**Comment by vikrambhatla** [comment]
> Same issue here +1 NestJS
> 
> _edit_ I was able to fix my coverage issue
> 
> @otroboe
> So for a controller you're gonna add an inject for the variable you're adding and an (or any)
> both are important because otherwise your specs are gonna break when the TestModule tries to create it, you'll get this error
> 
> " Error: Nest can't resolve dependencies of the ShowController (?). Please verify whether [0] argument is available in the current context. "
> 
> if you only add `| any`
> 
> so it'll look something like this
> 
> ```
> import { Get, Res, Controller } from '@nestjs/common';
> import { SomeService } from './some.service';
> import { Inject } from '@nestjs/common/utils/decorators/inject.decorator';
> 
> @Controller('somes')
> export class SomeController {
>     constructor(@Inject(SomeService) private readonly somesService: SomeService | any) {}
> 
>     @Get()
>     async index(@Res() response) {
>         const somes = this.somesService.all();
>         response.send({ somes });
>     }
> }
> ```
> 
> for a service, the `| any` is enough and it'll look something like this
> 
> ```
> import { Component } from '@nestjs/common';
> import { InjectRepository } from '@nestjs/typeorm';
> import { Repository } from 'typeorm';
> import { Some } from './some.entity';
> 
> @Component()
> export class SomeService {
>     constructor(
>         @InjectRepository(Some)
>         private readonly someRepository: Repository<Some> | any,
>     ) {}
> 
>     async all(): Promise<Some[]> {
>         return await this.someRepository.find();
>     }
> }
> ```
> 
> It may be the case that what you lose is type-ahead and type-checking, (I didn't have that issue) but you get 100% code-coverage in return. So it's up to your discretion.

Thanks for your answer. It works for me. I am able to get 100% coverage 👍 
`export class UserService {
    constructor(@Inject(HttpClient) private httpClient: HttpClient | any) {}

}`

**Comment by AaronEC-HMX** [comment]
Is there any update on this issue?  Still seeing constructor coverage gaps with `typescript: "3.8.3"`, `ts-jest: "26.0.0"`, and `jest-preset-angular: "8.1.3"`.

![image](https://user-images.githubusercontent.com/69807474/96063262-8b827300-0e65-11eb-9a30-6434af63e8b1.png)

This issue seems to present on HttpClient injection, and the `| any` solution is less than ideal in this case, as it prevents providing an expected type for the HTTP response.

![image](https://user-images.githubusercontent.com/69807474/96065186-4c085680-0e66-11eb-970d-1c8b3050b692.png)

**Comment by alecgibson** [comment]
For anyone using Webpack with `istanbul-instrumenter-loader`, we solved this by basically copying the [`ts-jest` solution](https://github.com/kulshekhar/ts-jest/pull/488) and adding a little wrapper:

```js
const istanbulInstrumenter = require('istanbul-instrumenter-loader');

exports.default = function(source, sourceMap) {
  // Ignore decorators on methods and properties
  source = source.replace(/(tslib.+\.__decorate)/g, '/* istanbul ignore next */$1');
  // When constructor parameters have decorated properties (eg @inject), TS adds
  // a typeof branch check, which we don't want to instrument
  source = source.replace(/(typeof \(_\w\s*=)/g, '/* istanbul ignore next */$1');

  istanbulInstrumenter.apply(this, [source, sourceMap]);
}
```

Then you replace your usage of the loader in your Webpack config:

```
{
    test: /\.[tj]sx?$/,
    use: {
      loader: path.resolve(__dirname, 'webpack', 'istanbul-instrumenter.js'),
      options: {
        esModules: true,
      },
    },
}
```

**Comment by stevengunneweg** [comment]
I also encountered this issue. After much searching it turned out that the link to my tsconfig was incorrect.
In my `jest.config.js` I had
```tsconfig: '<rootDir>/src/tsconfig.spec.json'```
When I changed it to
```tsconfig: 'src/tsconfig.spec.json'```
the issues were resolved. Aparently "\<rootDir\>" can't be used here.
I guess it was the same issue as https://github.com/istanbuljs/istanbuljs/issues/70#issuecomment-464271518 addresses in the end.
I still need to keep `isolatedModules` to "false" unfortunately.

**Comment by vad3x** [comment]
I've ended up with this workaround (similar to what @alecgibson has). Works for anyone who use bare `ts-jest`:

```js
// fix-istanbul-decorators.js

const { default: tsJest } = require('ts-jest');

module.exports = fixIstanbulDecoratorCoverageTransformer();

function fixIstanbulDecoratorCoverageTransformer() {
  const transformer = tsJest.createTransformer();
  const process = transformer.process.bind(transformer);
  transformer.process = (...args) => {
    let result = process(...args);
    // Ignore decorators on methods and properties
    result = result.replace(
      /__decorate/g,
      '/* istanbul ignore next */__decorate',
    );

    // When constructor parameters have decorated properties (eg @inject), TS adds
    // a typeof branch check, which we don't want to instrument
    result = result.replace(
      /(typeof \(_\w\s*=)/g,
      '/* istanbul ignore next */$1',
    );

    return result;
  };

  return transformer;
}
```

```js
// jest.config.js

...

  globals: {
    'ts-jest': {
      isolatedModules: true,
    },
  },
  transform: {
    '\\.(ts|tsx)$': '<rootDir>/fix-istanbul-decorators.js',
  },
...

```

Ref: https://github.com/kulshekhar/ts-jest/issues/1166#issuecomment-975650682

**Comment by micalevisk** [comment]
for `jest@28` the solution above will now be the following:

```
// fix-istanbul-decorators.js

// See https://github.com/istanbuljs/istanbuljs/issues/70#issuecomment-975654329
const { default: tsJest } = require('ts-jest');

module.exports = fixIstanbulDecoratorCoverageTransformer();

function fixIstanbulDecoratorCoverageTransformer() {
  const transformer = tsJest.createTransformer();
  const process = transformer.process.bind(transformer);
  transformer.process = (...args) => {
    let result = process(...args);
    // Ignore decorators on methods and properties
    result.code = result.code.replace(/__decorate/g, '/* istanbul ignore next */__decorate');

    // When constructor parameters have decorated properties (eg @inject), TS adds
    // a typeof branch check, which we don't want to instrument
    result.code = result.code.replace(
      /(?<=__metadata\("design:paramtypes".*?)(typeof \(_\w\s*=)/g,
      '/* istanbul ignore next */$1',
    );

    return result;
  };

  return transformer;
}
```

see https://jestjs.io/docs/upgrading-to-jest28#transformer

**Comment by mandarini** [comment]
We are facing the same issue, and this happens only when we're using 

```
    'ts-jest': {
      isolatedModules: true,
    },
```

The solutions provided in the comments (eg. [this](https://github.com/kulshekhar/ts-jest/issues/1166#issuecomment-975650682) and [this](https://github.com/istanbuljs/istanbuljs/issues/70#issuecomment-975654329)) do not seem to have any effect.

@micalevisk @vad3x these solutions do not seem to have an effect on my end.

I can see that the transformer is getting executed/added (I added a `console.log` just after the `const process = ...`), but it does not have any effect in my files, it's not doing any replacements. For the record, I put another `console.log` inside the actual transformer (inside `transformer.process = (...args) => { console.log('hi')...`) but it did not appear anywhere. 

Would you have any advice/tips as to where I could be doing something wrong, and not being able to get the replacements to happen?

**Comment by michaelfaith** [comment]
Experiencing this now after upgrading from Angular 14.1 to Angular 14.2 (using Yarn workspace, not sure about npm).  Any suggestions?   I'm not using isolatedModules, so I don't know that @mandarini's solution applies to me.  And I'm using `jest-preset-angular` rather than bare `ts-jest`, so I can't really change the transformer out like the other suggestions.

**Comment by mandarini** [comment]
Hi @michaelfaith ! My hacky solution does use `jest-preset-angular`! I just import it in the [hacky transformation](https://github.com/mandarini/isolatedm-jest/blob/main/fix-istanbul-decorators.js#L14). Again, I'm not saying it's a solution, since it's hacky, but rather a workaround. It would be nice to have an actual solution from `istanbul`...

**Comment by michaelfaith** [comment]
Thanks.  I guess I thought your solution was focused on solving this for people using `isolatedModules` turned on, which I don't have, currently.  I'll give it a try, though.

**Comment by matthewtquinn1** [comment]
Recently moved from Angular 13 to Angular 14.4.0 and this is now a problem for our code coverage.
Angular: 14.4.0
jest: 28.1.3
jest-preset-angular: 12.2.3
ts-jest: 28.0.8

Is there a fix available for this? All of my constructors are flagging up now as branches that are not covered

**Comment by michaelfaith** [comment]
> Recently moved from Angular 13 to Angular 14.4.0 and this is now a problem for our code coverage. Angular: 14.4.0 jest: 28.1.3 jest-preset-angular: 12.2.3 ts-jest: 28.0.8
> 
> Is there a fix available for this? All of my constructors are flagging up now as branches that are not covered

What finally solved this issue for us in Angular v14 was removing  `"emitDecoratorMetadata": true,` from the tsconfig.  Apparently it was no longer needed after v12, and for whatever reason was causing this issue in testing after 14.2

**Comment by matthewtquinn1** [comment]
Yep, that solved it! Thanks very much @michaelfaith 😃

**Comment by mandarini** [comment]
Nice @michaelfaith ! Is this valid even for `isolatedModules: true`?

**Comment by michaelfaith** [comment]
I haven't tried it with `isolatedModules`, and last time I turned that setting on, 80% of my tests failed.

**Comment by dotmobo** [comment]
Thanks @michaelfaith, it works with Angular 14 !

**Comment by sans-jmansfield** [comment]
This is still an issue when `emitDecoratorMetadata: false` is not a viable option for a given implementation and changing Angular versions is not relevant, e.g. when testing a NestJS application.

![image](https://user-images.githubusercontent.com/97901706/222203561-46402f22-3090-4dc9-b2b9-5f49a5e4c944.png)

**Comment by AydenOwl** [comment]
Hi guys, 

First: thank you @micalevisk for your file ! :) For my project, it was just missing one thing to work properly and to remove this warning: `[(WARN) Define `ts-jest` config under `globals` is deprecated](https://stackoverflow.com/questions/75955311/warn-define-ts-jest-config-under-globals-is-deprecated)`.

@sans-jmansfield I think it could solve your problem, I'm using Nest too and all is good now. 

My configuration:
"jest": "29.1.0"
"ts-jest": "29.1.0",
"@nestjs/common": "^8.0.0"

fix-istanbul-decorator.js: 

```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { default: tsJest } = require('ts-jest')

module.exports = fixIstanbulDecoratorCoverageTransformer()

function fixIstanbulDecoratorCoverageTransformer() {
  // The option of isolatedModules was necessary for me
  const transformer = tsJest.createTransformer({ isolatedModules: true })

  const process = transformer.process.bind(transformer)

  transformer.process = (...args) => {
    let result = process(...args)

    // Ignore decorators on methods and properties
    result.code = result.code.replace(/__decorate/g, '/* istanbul ignore next */__decorate')

    // When constructor parameters have decorated properties (eg @inject), TS adds
    // a typeof branch check, which we don't want to instrument
    result.code = result.code.replace(
      /(?<=__metadata\("design:paramtypes".*?)(typeof \(_\w\s*=)/g,
      '/* istanbul ignore next */$1'
    )

    return result
  }

  return transformer
}

```

jest.config.js:

```js
module.exports = {
  ...,
    moduleNameMapper: {
    '^src(.*)$': '<rootDir>/src/$1',
    // Related to this: https://jestjs.io/docs/28.x/upgrading-to-jest28#packagejson-exports
    uuid: require.resolve('uuid')
  },
  transform: {
    '\\.(ts|tsx)$': '<rootDir>/fix-istanbul-decorators.js'
  },
  ...
}
```

Hope it will help !

**Comment by amitkumar3400** [comment]
just replace your class closing curly brace "}" with } /* istanbul ignore next */
you can just add /* istanbul ignore next */ to the last closing curly brace and it would work

**Comment by aaronclawrence** [comment]
Just a note here, I tried the transform workaround given by [AydenOwl](https://github.com/istanbuljs/istanbuljs/issues/70#issuecomment-1564101539).
It does appear to work whilst leaving `emitDecoratorMetadata` on. 

But: it took 4 times as long to run the tests!

Thats not a cost we can easily wear...
